### ISSUE TITLE
cmus-remote returned unknown data

### ISSUE THREAD

**Issue by GideonWolfe** [Noah2610/cmus-status-line#8]
Running the base command returns:

```
ERROR:
cmus-remote returned unknown data: tag artist Streetlight Manifesto
Exiting.
```

**Comment by Noah2610** [comment]
@GideonWolfe 
Hey, thanks for the issue!
The error comes from simply having a track with some meta tags.
I guess I never used tracks with meta tags, so I never came across this.

It's fixed in the latest commit, I'll publish it on crates.io soon.
I've got some ideas now, about configuring it to display tag data in the output.

**Comment by Noah2610** [comment]
The fix is published on crates.io (v1.1.0)

**Comment by GideonWolfe** [comment]
Awesome!
